// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopEntertainment.Ordenes.AccessData;

#nullable disable

namespace TopEntertainment.Ordenes.AccessData.Migrations
{
    [DbContext(typeof(OrdenesContext))]
    partial class OrdenesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TopEntertainment.Ordenes.Domain.Entities.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EstadoID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasMaxLength(45)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoID");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("TopEntertainment.Ordenes.Domain.Entities.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarritoId")
                        .HasMaxLength(45)
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("date");

                    b.Property<float>("ImporteFinal")
                        .HasMaxLength(50)
                        .HasColumnType("real");

                    b.Property<int>("UsuarioId")
                        .HasMaxLength(45)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("TopEntertainment.Ordenes.Domain.Entities.EstadoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EstadoDetalles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 0
                        },
                        new
                        {
                            Id = 2,
                            Estado = 0
                        });
                });

            modelBuilder.Entity("TopEntertainment.Ordenes.Domain.Entities.JuegoCarrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CarritoID")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarritoID");

                    b.ToTable("JuegoCarrito");
                });

            modelBuilder.Entity("TopEntertainment.Ordenes.Domain.Entities.Carrito", b =>
                {
                    b.HasOne("TopEntertainment.Ordenes.Domain.Entities.EstadoDetalle", "estado")
                        .WithMany("carritosEstado")
                        .HasForeignKey("EstadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estado");
                });

            modelBuilder.Entity("TopEntertainment.Ordenes.Domain.Entities.JuegoCarrito", b =>
                {
                    b.HasOne("TopEntertainment.Ordenes.Domain.Entities.Carrito", "Carrito")
                        .WithMany("Carritos")
                        .HasForeignKey("CarritoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("TopEntertainment.Ordenes.Domain.Entities.Carrito", b =>
                {
                    b.Navigation("Carritos");
                });

            modelBuilder.Entity("TopEntertainment.Ordenes.Domain.Entities.EstadoDetalle", b =>
                {
                    b.Navigation("carritosEstado");
                });
#pragma warning restore 612, 618
        }
    }
}
